/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AppRightSidebar: typeof import('./../components/AppRightSidebar.vue')['default']
    AppSidebar: typeof import('./../components/AppSidebar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    CommonSocialNetworkLogo: typeof import('./../components/common/SocialNetworkLogo.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FeedCreatePost: typeof import('./../components/feed/CreatePost.vue')['default']
    FeedSocialAvatar: typeof import('./../components/feed/SocialAvatar.vue')['default']
    FeedSocialComment: typeof import('./../components/feed/SocialComment.vue')['default']
    FeedSocialPost: typeof import('./../components/feed/SocialPost.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    LocaleSwitch: typeof import('./../components/LocaleSwitch.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
  }
}
