/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/action-popup/': RouteRecordInfo<'/action-popup/', '/action-popup', Record<never, never>, Record<never, never>>,
    '/action-popup/playground': RouteRecordInfo<'/action-popup/playground', '/action-popup/playground', Record<never, never>, Record<never, never>>,
    '/common/404': RouteRecordInfo<'/common/404', '/common/404', Record<never, never>, Record<never, never>>,
    '/common/about': RouteRecordInfo<'/common/about', '/common/about', Record<never, never>, Record<never, never>>,
    '/common/change-log': RouteRecordInfo<'/common/change-log', '/common/change-log', Record<never, never>, Record<never, never>>,
    '/common/features': RouteRecordInfo<'/common/features', '/common/features', Record<never, never>, Record<never, never>>,
    '/common/help': RouteRecordInfo<'/common/help', '/common/help', Record<never, never>, Record<never, never>>,
    '/common/privacy-policy': RouteRecordInfo<'/common/privacy-policy', '/common/privacy-policy', Record<never, never>, Record<never, never>>,
    '/common/terms-of-service': RouteRecordInfo<'/common/terms-of-service', '/common/terms-of-service', Record<never, never>, Record<never, never>>,
    '/content-script-iframe/': RouteRecordInfo<'/content-script-iframe/', '/content-script-iframe', Record<never, never>, Record<never, never>>,
    '/devtools-panel/': RouteRecordInfo<'/devtools-panel/', '/devtools-panel', Record<never, never>, Record<never, never>>,
    '/options-page/': RouteRecordInfo<'/options-page/', '/options-page', Record<never, never>, Record<never, never>>,
    '/setup/install': RouteRecordInfo<'/setup/install', '/setup/install', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz': RouteRecordInfo<'/setup/SocialGlowz', '/setup/SocialGlowz', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/App': RouteRecordInfo<'/setup/SocialGlowz/App', '/setup/SocialGlowz/App', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/AppHeader': RouteRecordInfo<'/setup/SocialGlowz/components/AppHeader', '/setup/SocialGlowz/components/AppHeader', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/AppRightSidebar': RouteRecordInfo<'/setup/SocialGlowz/components/AppRightSidebar', '/setup/SocialGlowz/components/AppRightSidebar', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/AppSettings': RouteRecordInfo<'/setup/SocialGlowz/components/AppSettings', '/setup/SocialGlowz/components/AppSettings', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/AppSidebar': RouteRecordInfo<'/setup/SocialGlowz/components/AppSidebar', '/setup/SocialGlowz/components/AppSidebar', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/BackupRestore': RouteRecordInfo<'/setup/SocialGlowz/components/BackupRestore', '/setup/SocialGlowz/components/BackupRestore', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/BillingAccessPanel': RouteRecordInfo<'/setup/SocialGlowz/components/BillingAccessPanel', '/setup/SocialGlowz/components/BillingAccessPanel', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/common/NetworkLogo': RouteRecordInfo<'/setup/SocialGlowz/components/common/NetworkLogo', '/setup/SocialGlowz/components/common/NetworkLogo', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/common/SocialNetworkLogo': RouteRecordInfo<'/setup/SocialGlowz/components/common/SocialNetworkLogo', '/setup/SocialGlowz/components/common/SocialNetworkLogo', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/DashboardFilters': RouteRecordInfo<'/setup/SocialGlowz/components/DashboardFilters', '/setup/SocialGlowz/components/DashboardFilters', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/ExtensionParitySurface': RouteRecordInfo<'/setup/SocialGlowz/components/ExtensionParitySurface', '/setup/SocialGlowz/components/ExtensionParitySurface', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/feed/CreatePost': RouteRecordInfo<'/setup/SocialGlowz/components/feed/CreatePost', '/setup/SocialGlowz/components/feed/CreatePost', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/feed/SocialAvatar': RouteRecordInfo<'/setup/SocialGlowz/components/feed/SocialAvatar', '/setup/SocialGlowz/components/feed/SocialAvatar', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/feed/SocialComment': RouteRecordInfo<'/setup/SocialGlowz/components/feed/SocialComment', '/setup/SocialGlowz/components/feed/SocialComment', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/feed/SocialPost': RouteRecordInfo<'/setup/SocialGlowz/components/feed/SocialPost', '/setup/SocialGlowz/components/feed/SocialPost', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/FriendsPanel': RouteRecordInfo<'/setup/SocialGlowz/components/FriendsPanel', '/setup/SocialGlowz/components/FriendsPanel', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/icons/NextdoorIcon': RouteRecordInfo<'/setup/SocialGlowz/components/icons/NextdoorIcon', '/setup/SocialGlowz/components/icons/NextdoorIcon', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/icons/QuoraIcon': RouteRecordInfo<'/setup/SocialGlowz/components/icons/QuoraIcon', '/setup/SocialGlowz/components/icons/QuoraIcon', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/icons/SnapchatIcon': RouteRecordInfo<'/setup/SocialGlowz/components/icons/SnapchatIcon', '/setup/SocialGlowz/components/icons/SnapchatIcon', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/icons/ThreadsIcon': RouteRecordInfo<'/setup/SocialGlowz/components/icons/ThreadsIcon', '/setup/SocialGlowz/components/icons/ThreadsIcon', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/kanban/KanbanBoard': RouteRecordInfo<'/setup/SocialGlowz/components/kanban/KanbanBoard', '/setup/SocialGlowz/components/kanban/KanbanBoard', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/kanban/KanbanSidebar': RouteRecordInfo<'/setup/SocialGlowz/components/kanban/KanbanSidebar', '/setup/SocialGlowz/components/kanban/KanbanSidebar', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/MobileLayout': RouteRecordInfo<'/setup/SocialGlowz/components/MobileLayout', '/setup/SocialGlowz/components/MobileLayout', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/MobileProfileSheet': RouteRecordInfo<'/setup/SocialGlowz/components/MobileProfileSheet', '/setup/SocialGlowz/components/MobileProfileSheet', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/MobileSettingsSheet': RouteRecordInfo<'/setup/SocialGlowz/components/MobileSettingsSheet', '/setup/SocialGlowz/components/MobileSettingsSheet', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/DiscordView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/DiscordView', '/setup/SocialGlowz/components/networks/DiscordView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/FacebookView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/FacebookView', '/setup/SocialGlowz/components/networks/FacebookView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/GmailView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/GmailView', '/setup/SocialGlowz/components/networks/GmailView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/InstagramView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/InstagramView', '/setup/SocialGlowz/components/networks/InstagramView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/LinkedInView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/LinkedInView', '/setup/SocialGlowz/components/networks/LinkedInView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/RedditView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/RedditView', '/setup/SocialGlowz/components/networks/RedditView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/SnapchatView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/SnapchatView', '/setup/SocialGlowz/components/networks/SnapchatView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/ThreadsView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/ThreadsView', '/setup/SocialGlowz/components/networks/ThreadsView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/TikTokView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/TikTokView', '/setup/SocialGlowz/components/networks/TikTokView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/networks/TwitterView': RouteRecordInfo<'/setup/SocialGlowz/components/networks/TwitterView', '/setup/SocialGlowz/components/networks/TwitterView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/NetworkWebviewHost': RouteRecordInfo<'/setup/SocialGlowz/components/NetworkWebviewHost', '/setup/SocialGlowz/components/NetworkWebviewHost', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/OnboardingFlow': RouteRecordInfo<'/setup/SocialGlowz/components/OnboardingFlow', '/setup/SocialGlowz/components/OnboardingFlow', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/PostAuthSyncOverlay': RouteRecordInfo<'/setup/SocialGlowz/components/PostAuthSyncOverlay', '/setup/SocialGlowz/components/PostAuthSyncOverlay', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/ProfileSwitcher': RouteRecordInfo<'/setup/SocialGlowz/components/ProfileSwitcher', '/setup/SocialGlowz/components/ProfileSwitcher', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/SignupNudge': RouteRecordInfo<'/setup/SocialGlowz/components/SignupNudge', '/setup/SocialGlowz/components/SignupNudge', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/SocialLogin': RouteRecordInfo<'/setup/SocialGlowz/components/SocialLogin', '/setup/SocialGlowz/components/SocialLogin', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/components/Unauthorized': RouteRecordInfo<'/setup/SocialGlowz/components/Unauthorized', '/setup/SocialGlowz/components/Unauthorized', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/views/LoginView': RouteRecordInfo<'/setup/SocialGlowz/views/LoginView', '/setup/SocialGlowz/views/LoginView', Record<never, never>, Record<never, never>>,
    '/setup/SocialGlowz/views/SessionLockView': RouteRecordInfo<'/setup/SocialGlowz/views/SessionLockView', '/setup/SocialGlowz/views/SessionLockView', Record<never, never>, Record<never, never>>,
    '/setup/update': RouteRecordInfo<'/setup/update', '/setup/update', Record<never, never>, Record<never, never>>,
    '/side-panel/': RouteRecordInfo<'/side-panel/', '/side-panel', Record<never, never>, Record<never, never>>,
  }
}
